### ISSUE TITLE
Contribution to ACS Commons

### ISSUE THREAD

**Issue by ghost** [mickleroy/aem-sass-compiler#11]
Hey, love the idea for this project. I always thought it was kind of strange that AEM did not support SASS compilation.

Do you think this would be a good idea to contribute to ACS Commons? I think that might increase exposure and support for this project.

**Comment by mickleroy** [comment]
Thanks for the support!
I've spoken to Justin about it and he's happy to bring this into ACS Commons. Just need to find the time to do it 😄
