### ISSUE TITLE
A new jsass release 5.7.3 is available with a more recent sass version: 3.5.4

### ISSUE THREAD

**Issue by ieugen** [mickleroy/aem-sass-compiler#13]
Hello,

It seems a new jsass version is available with a more recent sass version : 3.5.4  https://github.com/bit3/jsass/commits/master  

It would be nice to see this reflected in this plugin as well. I think a minor version bump would be in order as it seems the sass syntax changed. 

Regards,

**Comment by esr360** [comment]
+1, also it would be nice if the readme stated which version of Sass was currently in use rather than stating "Supports all the latest features of Sass" which at this point is incorrect.

**Comment by besimhu** [comment]
+1 for this update @mickleroy

**Comment by mickleroy** [comment]
v1.0.4 contains jsass version 5.7.3. Thanks for letting me know!
