### ISSUE TITLE
Parent selector not working

### ISSUE THREAD

**Issue by prakashkumarsb** [mickleroy/aem-sass-compiler#15]
Hi @mickleroy ,

When we use parent selector (<), its not compiling back to css. throwing exception.

**Line of code used**- p < .small { margin: 0; }
**Exception**-23.03.2019 22:24:34.719 *ERROR* [0:0:0:0:0:0:0:1 [1553340274635] GET /etc/designs/test/clientlib-test.css HTTP/1.1] com.github.mickleroy.aem.sass.impl.SassCompilerImpl Failed to compile Sass /apps/test/clientlib-site/css/main.scss: Error: Invalid CSS after "}": expected 1 selector or at-rule, was "p < .small { margin"
        on line 117 of ../../../../../../../apps/test/clientlib-site/css/_base.scss
>> }
   -^

**Comment by mickleroy** [comment]
Hi @SBPrakash, can you please link me to documentation about the parent selector in Sass? I can't seem to find any reference to it..

**Comment by prakashkumarsb** [comment]
@mickleroy Here it is 
https://stackoverflow.com/questions/1014861/is-there-a-css-parent-selector
https://css-tricks.com/parent-selectors-in-css/

**Comment by mickleroy** [comment]
Thanks. The article is pretty clear - the parent selector isn't implemented in CSS3 or Sass:

> Let's be clear here, just in case someone is finding this from a search engine: there are no parent selectors in CSS, not even in CSS3.
