### ISSUE TITLE
AEM 6.1 support

### ISSUE THREAD

**Issue by mickleroy** [mickleroy/aem-sass-compiler#3]
Uploading the bundle in an AEM 6.1 instance isn't working either. Need to provide support for that if possible.

**Comment by felipe4253** [comment]
Hi @mickleroy ,
What is exactly preventing it from work on AEM 6.1?
I've deployed it on 6.1 and the problem I noticed is that the bundle cannot import this specific package:
"com.adobe.granite.ui.clientlibs.script,version=[1.1,2)"

Is it the only problem running on AEM 6.1 or you found another issue?

Thanks!

**Comment by mickleroy** [comment]
Hi @felipe4253,

Unfortunately, getting the compiler working in 6.1 wasn't as easy as downgrading the uber jar version. The problem I ran into was a `VerifyError` in the `com.adobe.granite.ui.clientlibs.script.Utils` class when using the 6.1 uber jar. 

I was only able to get this working with 6.1 SP2 and I've created release [0.9.0](https://github.com/mickleroy/aem-sass-compiler/releases/tag/v0.9.0) for AEM 6.1 SP2 support.

**Comment by felipe4253** [comment]
All right @mickleroy! This perfectly fit what I need here!

Thank you!

**Comment by phoenixwizard** [comment]
Can the 0.9.0 version also have a fix for https://github.com/mickleroy/aem-sass-compiler/issues/4 ?
Or maybe suggest a workaround for this @mickleroy ?

**Comment by mickleroy** [comment]
Hi @phoenixwizard, there's various workarounds listed in #4 like clearing the clientlibs cache or modifying the main sass file. In any case, I'll cherry pick the fix into a new 0.9.X release. I'll let you know once it's available on Maven Central.

**Comment by mickleroy** [comment]
@phoenixwizard release 0.9.1 contains the dependencies fix.
